# Generated by Django 5.1.7 on 2025-04-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('Pediatra', 'pediatra'), ('Cardiologia', 'padiatra'), ('Cirurgia plástica', 'Cirurgia plástica'), ('Neurologia', 'Neurologia'), ('Radiologia', 'Radiologia'), ('Nenhuma das opções', 'Nenhuma das opções')], max_length=200)),
                ('crm', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('agendado', 'agendado'), ('realizado', 'realizado'), ('cancelado', 'cancelado')], max_length=200)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
